### ISSUE TITLE
async issues perhaps when it needs to download too many images?

### ISSUE THREAD

**Issue by Jonius7** [wynick27/steam-missing-covers-downloader#18]
I was doing some tests with the downloader and for some reason it sometimes fails. My full library without any images requires 301 images to be downloaded and these errors pop up:

https://pastebin.com/xbnZakvV

It fails to download any images to the `grid` folder.
However if I copy most of my images in and have it download 100 images, or a couple of images, it successfully downloads them, but still has `Event loop is closed` errors

**Comment by barryjj** [comment]
I found a reference to why the Event loop is closed errors are showing up.

https://github.com/encode/httpx/issues/914#issuecomment-622586610

Using the workaround code from there in missing_cover_downloader.py fixed the issue with asyncio and event loops.

**Comment by Jonius7** [comment]
Fixed in 407e820ec43b61d1f4329a4703a92010b6707ff2
