### ISSUE TITLE
Downloads games I don't own

### ISSUE THREAD

**Issue by jondycz** [wynick27/steam-missing-covers-downloader#5]
For some reason the script just downloaded bunch of games I don't own, so I stopped it. I'm not sitting here downloading 26 000 game covers.

**Comment by wynick27** [comment]
That's because previously reading packageinfo is not implemented. So the script reads entire appcache to look for games. And even if only one user logged into steam, there are usually more games in appcache. I've fixed this in version 1.5.0.
